# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MainWindow.ui'
#
# Created: Tue Sep 02 22:35:15 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(914, 698)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tab_display = QtGui.QTabWidget(self.centralwidget)
        self.tab_display.setObjectName(_fromUtf8("tab_display"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.previewerBox = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewerBox.sizePolicy().hasHeightForWidth())
        self.previewerBox.setSizePolicy(sizePolicy)
        self.previewerBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.previewerBox.setObjectName(_fromUtf8("previewerBox"))
        self.gridLayout = QtGui.QGridLayout(self.previewerBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.table_node_info = QtGui.QTableWidget(self.previewerBox)
        self.table_node_info.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_node_info.setColumnCount(0)
        self.table_node_info.setObjectName(_fromUtf8("table_node_info"))
        self.table_node_info.setRowCount(0)
        self.gridLayout.addWidget(self.table_node_info, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.previewerBox)
        self.groupBox = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(280, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.lcdNumber_time = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumber_time.setMinimumSize(QtCore.QSize(0, 40))
        self.lcdNumber_time.setFrameShape(QtGui.QFrame.Box)
        self.lcdNumber_time.setFrameShadow(QtGui.QFrame.Raised)
        self.lcdNumber_time.setLineWidth(1)
        self.lcdNumber_time.setMidLineWidth(0)
        self.lcdNumber_time.setNumDigits(8)
        self.lcdNumber_time.setObjectName(_fromUtf8("lcdNumber_time"))
        self.verticalLayout.addWidget(self.lcdNumber_time)
        self.lcdNumber_date = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumber_date.setMinimumSize(QtCore.QSize(0, 40))
        self.lcdNumber_date.setNumDigits(10)
        self.lcdNumber_date.setObjectName(_fromUtf8("lcdNumber_date"))
        self.verticalLayout.addWidget(self.lcdNumber_date)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.button_setup_time = QtGui.QPushButton(self.groupBox)
        self.button_setup_time.setEnabled(True)
        self.button_setup_time.setMinimumSize(QtCore.QSize(125, 50))
        self.button_setup_time.setMaximumSize(QtCore.QSize(120, 16777215))
        self.button_setup_time.setObjectName(_fromUtf8("button_setup_time"))
        self.horizontalLayout_4.addWidget(self.button_setup_time)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtGui.QTextEdit(self.groupBox)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.splitter = QtGui.QSplitter(self.groupBox)
        self.splitter.setMinimumSize(QtCore.QSize(0, 50))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.button_scan = QtGui.QPushButton(self.splitter)
        self.button_scan.setCheckable(False)
        self.button_scan.setObjectName(_fromUtf8("button_scan"))
        self.button_open_serial = QtGui.QPushButton(self.splitter)
        self.button_open_serial.setMinimumSize(QtCore.QSize(0, 0))
        self.button_open_serial.setObjectName(_fromUtf8("button_open_serial"))
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.tab_display.addTab(self.tab, _fromUtf8(""))
        self.tab_fig = QtGui.QWidget()
        self.tab_fig.setObjectName(_fromUtf8("tab_fig"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_fig)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_fig)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter_4 = QtGui.QSplitter(self.groupBox_3)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.splitter_3 = QtGui.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.table_plot_node = QtGui.QTableWidget(self.splitter_3)
        self.table_plot_node.setMaximumSize(QtCore.QSize(200, 16777215))
        self.table_plot_node.setColumnCount(0)
        self.table_plot_node.setObjectName(_fromUtf8("table_plot_node"))
        self.table_plot_node.setRowCount(0)
        self.combo_plot_range = QtGui.QComboBox(self.splitter_3)
        self.combo_plot_range.setMaximumSize(QtCore.QSize(16777215, 40))
        self.combo_plot_range.setObjectName(_fromUtf8("combo_plot_range"))
        self.combo_plot_range.addItem(_fromUtf8(""))
        self.combo_plot_range.addItem(_fromUtf8(""))
        self.combo_plot_range.addItem(_fromUtf8(""))
        self.combo_plot_range.addItem(_fromUtf8(""))
        self.combo_plot_range.addItem(_fromUtf8(""))
        self.combo_plot_range.addItem(_fromUtf8(""))
        self.combo_plot_range.addItem(_fromUtf8(""))
        self.combo_plot_range.addItem(_fromUtf8(""))
        self.qwtPlot = Qwt5.QwtPlot(self.splitter_4)
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self.gridLayout_2.addWidget(self.splitter_4, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.tab_display.addTab(self.tab_fig, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.table_range_display = QtGui.QTableWidget(self.groupBox_2)
        self.table_range_display.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.table_range_display.setObjectName(_fromUtf8("table_range_display"))
        self.table_range_display.setColumnCount(0)
        self.table_range_display.setRowCount(0)
        self.verticalLayout_2.addWidget(self.table_range_display)
        self.splitter_2 = QtGui.QSplitter(self.groupBox_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.label_3 = QtGui.QLabel(self.splitter_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line_config_status = QtGui.QLineEdit(self.splitter_2)
        self.line_config_status.setObjectName(_fromUtf8("line_config_status"))
        self.pushButton_config = QtGui.QPushButton(self.splitter_2)
        self.pushButton_config.setObjectName(_fromUtf8("pushButton_config"))
        self.pushButton_save = QtGui.QPushButton(self.splitter_2)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.tab_display.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tab_display)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 914, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.menubar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menu_update_online = QtGui.QAction(MainWindow)
        self.menu_update_online.setObjectName(_fromUtf8("menu_update_online"))
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.action_3 = QtGui.QAction(MainWindow)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.menu_scan_node = QtGui.QAction(MainWindow)
        self.menu_scan_node.setObjectName(_fromUtf8("menu_scan_node"))
        self.action_5 = QtGui.QAction(MainWindow)
        self.action_5.setObjectName(_fromUtf8("action_5"))
        self.menu_save_config = QtGui.QAction(MainWindow)
        self.menu_save_config.setObjectName(_fromUtf8("menu_save_config"))
        self.action_8 = QtGui.QAction(MainWindow)
        self.action_8.setObjectName(_fromUtf8("action_8"))
        self.menu_exit = QtGui.QAction(MainWindow)
        self.menu_exit.setObjectName(_fromUtf8("menu_exit"))
        self.action_10 = QtGui.QAction(MainWindow)
        self.action_10.setObjectName(_fromUtf8("action_10"))
        self.action_11 = QtGui.QAction(MainWindow)
        self.action_11.setObjectName(_fromUtf8("action_11"))
        self.menu_config_serial = QtGui.QAction(MainWindow)
        self.menu_config_serial.setObjectName(_fromUtf8("menu_config_serial"))
        self.menu.addAction(self.menu_config_serial)
        self.menu.addAction(self.menu_scan_node)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_save_config)
        self.menu.addAction(self.action_8)
        self.menu.addAction(self.menu_exit)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_10)
        self.menu_2.addAction(self.action_11)
        self.menu_3.addAction(self.menu_update_online)
        self.menu_3.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_display.setCurrentIndex(0)
        QtCore.QObject.connect(self.menu_exit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.previewerBox.setTitle(_translate("MainWindow", "节点信息", None))
        self.groupBox.setTitle(_translate("MainWindow", "控制", None))
        self.label_2.setText(_translate("MainWindow", "时间日期：", None))
        self.button_setup_time.setText(_translate("MainWindow", "时间设置", None))
        self.label.setText(_translate("MainWindow", "提醒：", None))
        self.button_scan.setText(_translate("MainWindow", "扫描", None))
        self.button_open_serial.setText(_translate("MainWindow", "连接", None))
        self.tab_display.setTabText(self.tab_display.indexOf(self.tab), _translate("MainWindow", "显示", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "温湿度显示", None))
        self.combo_plot_range.setItemText(0, _translate("MainWindow", "最近1小时", None))
        self.combo_plot_range.setItemText(1, _translate("MainWindow", "最近3小时", None))
        self.combo_plot_range.setItemText(2, _translate("MainWindow", "最近12小时", None))
        self.combo_plot_range.setItemText(3, _translate("MainWindow", "最近1天", None))
        self.combo_plot_range.setItemText(4, _translate("MainWindow", "最近3天", None))
        self.combo_plot_range.setItemText(5, _translate("MainWindow", "最近1周", None))
        self.combo_plot_range.setItemText(6, _translate("MainWindow", "最近30天", None))
        self.combo_plot_range.setItemText(7, _translate("MainWindow", "全部", None))
        self.tab_display.setTabText(self.tab_display.indexOf(self.tab_fig), _translate("MainWindow", "曲线图", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "范围显示", None))
        self.label_3.setText(_translate("MainWindow", "信息显示：", None))
        self.pushButton_config.setText(_translate("MainWindow", "设置生效", None))
        self.pushButton_save.setText(_translate("MainWindow", "保存参数", None))
        self.tab_display.setTabText(self.tab_display.indexOf(self.tab_2), _translate("MainWindow", "设置", None))
        self.menu.setTitle(_translate("MainWindow", "操作", None))
        self.menu_2.setTitle(_translate("MainWindow", "视图", None))
        self.menu_3.setTitle(_translate("MainWindow", "帮助", None))
        self.menu_update_online.setText(_translate("MainWindow", "在线更新", None))
        self.action_2.setText(_translate("MainWindow", "关于", None))
        self.action_3.setText(_translate("MainWindow", "查看全部", None))
        self.menu_scan_node.setText(_translate("MainWindow", "扫描节点", None))
        self.action_5.setText(_translate("MainWindow", "增加节点", None))
        self.menu_save_config.setText(_translate("MainWindow", "保存设置", None))
        self.action_8.setText(_translate("MainWindow", "设置另存为", None))
        self.menu_exit.setText(_translate("MainWindow", "退出", None))
        self.action_10.setText(_translate("MainWindow", "单独查看", None))
        self.action_11.setText(_translate("MainWindow", "曲线视图", None))
        self.menu_config_serial.setText(_translate("MainWindow", "配置串口", None))

from PyQt4 import Qwt5

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

